// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcDZhETBfx2KfS-RbpeoeDdkvh70MwxI8',
    appId: '1:174609982242:web:668efc2b9859736dce7b7b',
    messagingSenderId: '174609982242',
    projectId: 'legalease-eb4b6',
    authDomain: 'legalease-eb4b6.firebaseapp.com',
    storageBucket: 'legalease-eb4b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC77FYpOWcIVHzdfA3IRWR7ze_bg3JZmSs',
    appId: '1:174609982242:android:7537b53dcf0cc12fce7b7b',
    messagingSenderId: '174609982242',
    projectId: 'legalease-eb4b6',
    storageBucket: 'legalease-eb4b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBinmGQ4vpOC3xA0U2f7MY-6vvYI1WmF5I',
    appId: '1:174609982242:ios:1b6f0b75f642d07dce7b7b',
    messagingSenderId: '174609982242',
    projectId: 'legalease-eb4b6',
    storageBucket: 'legalease-eb4b6.firebasestorage.app',
    iosClientId: '174609982242-emmlm3arjiousb2va4obik5b8tg0asod.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalEaseAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBinmGQ4vpOC3xA0U2f7MY-6vvYI1WmF5I',
    appId: '1:174609982242:ios:1b6f0b75f642d07dce7b7b',
    messagingSenderId: '174609982242',
    projectId: 'legalease-eb4b6',
    storageBucket: 'legalease-eb4b6.firebasestorage.app',
    iosClientId: '174609982242-emmlm3arjiousb2va4obik5b8tg0asod.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalEaseAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcDZhETBfx2KfS-RbpeoeDdkvh70MwxI8',
    appId: '1:174609982242:web:9f9cdb8d0a14d295ce7b7b',
    messagingSenderId: '174609982242',
    projectId: 'legalease-eb4b6',
    authDomain: 'legalease-eb4b6.firebaseapp.com',
    storageBucket: 'legalease-eb4b6.firebasestorage.app',
  );
}
